[[section:migration-to-jdk9]]

## Adapt the Maven build to use Java 9

So, first of all, we will update our Maven build so that it properly compiles Java 9 sources. This step is pretty basic, as we only have to adjust the configuration of the `maven-compiler-plugin` and - of course - environment variables, so that Maven can pick up the proper JDK.

[source,xml]
----
<plugins>
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.7.0</version>
    <configuration>
      <source>9</source>
      <target>9</target>
      <showWarnings>true</showWarnings>
      <showDeprecation>true</showDeprecation>
    </configuration>
  </plugin>
</plugins>
----

Depending on the settings on your local machine, you can either use a global `JAVA_HOME` environment variable that points to the JDK 9 or you can use the Maven Resource File (`~/.mavenrc`). Either way, your `PATH` variable should include a reference JDK 9.

On my machine, the path to JDK 9 is `/usr/lib/jvm/java-9-oracle`, so the configuration looks just like this:

[source,bash]
----
export JAVA_HOME=/usr/lib/jvm/java-9-oracle
export PATH=${PATH}:$JAVA_HOME/bin
----

Running a `mvn clean install` from the project source folder should still yield a success. The configuration of the `maven-compiler-plugin` states that we want to see any kind of warnings and deprecated usages during the build. In our particular case, there are none: Our string matching algorithms work perfectly fine up to this point.

This is expected as Java 9 can be used just like any previous version of Java. You do not have to commit to a fully modularized build to begin with. What happens if you do not is that any code outside of a specific module ends up in the so called _unnamed module_. The build will not break, since the unnamed module is able to read all other modules.

Please note that although you do not have to commit to the JPMS, the JDK itself is still modularized as of Java 9. This may lead to broken builds if you reference code that is not reachable through module `java.se`, which is the root module per default if you do not use designated modules for your code. This is for instance the case if your code uses the popular JAXB API.
