[[section:migration-matchers-cli]]

## Modularizing `matchers-cli`

Now if we issue a `mvn clean install` we run into a different error:

[source,bash]
----
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/mgu/workspace/string-matchers/matchers-cli/src/main/java/net/mguenther/matchers/MatchersCli.java:[3,35] package net.mguenther.matchers.impl does not exist
[ERROR] /home/mgu/workspace/string-matchers/matchers-cli/src/main/java/net/mguenther/matchers/MatchersCli.java:[4,35] package net.mguenther.matchers.impl does not exist
[ERROR] /home/mgu/workspace/string-matchers/matchers-cli/src/main/java/net/mguenther/matchers/MatchersCli.java:[25,9] cannot find symbol
  symbol:   class Matcher
  location: class net.mguenther.matchers.MatchersCli
[ERROR] /home/mgu/workspace/string-matchers/matchers-cli/src/main/java/net/mguenther/matchers/MatchersCli.java:[30,31] cannot find symbol
  symbol:   class KnuthMorrisPrattMatcher
  location: class net.mguenther.matchers.MatchersCli
[ERROR] /home/mgu/workspace/string-matchers/matchers-cli/src/main/java/net/mguenther/matchers/MatchersCli.java:[35,31] cannot find symbol
  symbol:   class BruteForceMatcher
  location: class net.mguenther.matchers.MatchersCli
[INFO] 5 errors
----

This is expected as our Maven module `matchers-cli` is not modularized with Jigsaw. We simply execute the same procedure again to modularize `matchers-cli` and provide the necessary `requires`-declarations along with the module descriptor.

For the time being the module descriptor will look like this (we will address visibility issues shortly):

[source,java]
----
module matchers.cli {
    requires matchers.api;
    requires matchers.impl;
}
----

This will make one thing very clear: `matchers.cli` still requires access to both implementation modules. This is not beneficial as the main purpose of the module system is to decouple Java modules from each other. Enter service loaders.

TODO

We will write some stuff about plug-in architectures and how great it would be if we can simply add modules containing algorithms to the module path and use the algorithms in our Java application (pluggable). For this, we will split `matchers.impl` into:

* `matchers.bruteforce`
* `matchers.kmp`

Due to the limitations of the Java module system, we will have to rename our packages as well:

* net.mguenther.matchers.bruteforce.BruteForceMatcher
* net.mguenther.matchers.kmp.KnuthMorrisPrattMatcher
