@startuml

skinparam shadowing false
skinparam componentStyle uml2
skinparam linetype ortho
skinparam frame {
    borderColor Transparent
    backgroundColor Transparent
    fontColor Transparent
}

component "<b>matchers-api</b>" <<Matchers API>> as matchersapi
component "<b>matchers-core</b>" <<String Matching Algorithms>> as matcherscore
component "<b>matchers-cli</b>" <<Matchers CLI>> as matcherscli

matcherscli ..> matchersapi
matcherscli ..> matcherscore
matcherscore ..> matchersapi

@enduml