@startuml

skinparam shadowing false
skinparam componentStyle uml2
skinparam linetype ortho
skinparam frame {
    borderColor Transparent
    backgroundColor Transparent
    fontColor Transparent
}

component "<b>matchers.api</b>" as matchersapi
component "<b>matchers.impl</b>" as matchersimpl
component "<b>matchers.cli</b>" as matcherscli

matcherscli ..> matchersapi
matcherscli ..> matchersimpl

matchersimpl ..> matchersapi

@enduml