@startuml

skinparam shadowing false
skinparam componentStyle uml2
skinparam linetype ortho
skinparam frame {
    borderColor Transparent
    backgroundColor Transparent
    fontColor Transparent
}

component "<b>java.base</b>" as javabase
component "<b>matchers.api</b>" as matchersapi
component "<b>matchers.impl</b>" as matcherscore
component "<b>matchers.cli</b>" as matcherscli

matcherscli ..> javabase
matcherscli ..> matchersapi
matcherscli ..> matcherscore

matchersapi ..> javabase

matcherscore ..> javabase
matcherscore ..> matchersapi

@enduml